on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package plugin
        run: ls 
       
#       - name: Upload artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: iceberg-wp-clients.zip
#           path: iceberg-wp-clients-plugin.zip
