on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package plugin
        run: |
          cd ..
          zip -r iceberg-wp-clients-plugin.zip . -x $(git ls-files -z --ignored --exclude-standard | xargs -0 printf "'%s' ")
       
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: iceberg-wp-clients.zip
          path: iceberg-wp-clients-plugin.zip
